-- Tus 数据库初始化脚本
-- 在 Supabase SQL Editor 中运行此脚本

-- 1. 创建科目表
CREATE TABLE IF NOT EXISTS subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    teacher TEXT DEFAULT '',
    description TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 创建试卷表
CREATE TABLE IF NOT EXISTS papers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    year INTEGER NOT NULL,
    semester TEXT DEFAULT '期末',
    file_url TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_size BIGINT DEFAULT 0,
    uploaded_by TEXT DEFAULT '匿名',
    download_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. 创建下载计数函数（用于 RPC 调用）
CREATE OR REPLACE FUNCTION increment_download_count(paper_id BIGINT)
RETURNS void AS $$
BEGIN
    UPDATE papers SET download_count = download_count + 1 WHERE id = paper_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. 开启 Row Level Security（行级安全）
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE papers ENABLE ROW LEVEL SECURITY;

-- 5. 创建公开访问策略（允许所有人读取和写入）
CREATE POLICY "公开读取科目" ON subjects FOR SELECT USING (true);
CREATE POLICY "公开创建科目" ON subjects FOR INSERT WITH CHECK (true);
CREATE POLICY "公开读取试卷" ON papers FOR SELECT USING (true);
CREATE POLICY "公开上传试卷" ON papers FOR INSERT WITH CHECK (true);

-- 6. 创建存储桶（在 Storage 页面执行，或使用下面的 SQL）
-- 注意：在 Supabase Dashboard > Storage 中创建一个名为 "papers" 的公开存储桶
-- 或者在 SQL 中运行：
-- INSERT INTO storage.buckets (id, name, public) VALUES ('papers', 'papers', true);
--
-- 然后设置公开访问策略：
-- CREATE POLICY "公开读取" ON storage.objects FOR SELECT USING (bucket_id = 'papers');
-- CREATE POLICY "公开上传" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'papers');